Use appPrefix and project prefix

diff --git a/destroy-environment/action.yaml b/destroy-environment/action.yaml
--- a/destroy-environment/action.yaml
+++ b/destroy-environment/action.yaml
@@ -40,8 +40,6 @@ runs:
         FEAT_NAME="${FEAT_FULL_NAME:0:30}"
         NAMESPACE=${{ inputs.namespacePrefix }}
 
-        echo "BRANCH_TYPE: $BRANCH_TYPE"
-
         if [[ "$BRANCH_TYPE" =~ ${{ env.REGEX_FEATURE_BRANCH }} ]] ; then
           export NAMESPACE+="-ft-"$FEAT_NAME
           export BRANCH_SHORT="ft-"$FEAT_NAME
@@ -52,4 +50,7 @@ runs:
           export BRANCH_SHORT="hot-"$FEAT_NAME
           echo "Deleting namespace $NAMESPACE for hotfix branch $BRANCH_LOWER"
           kubectl delete namespace $NAMESPACE
+        else
+          echo "Error branch type do not match"
+          exit 1;
         fi
